---
- name: Set zsh as the default shell for the user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  when: ansible_user_shell != '/bin/zsh'

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_stat

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  when: not ohmyzsh_stat.stat.exists

- name: Install and update Oh My Zsh plugins
  ansible.builtin.include_tasks: install_single_plugin.yml
  loop: "{{ zsh_plugins }}"
  loop_control:
    label: "{{ item.name }}"

- name: Deploy .env.zsh from template
  ansible.builtin.template:
    src: .env.zsh.j2
    dest: "{{ ansible_env.HOME }}/.env.zsh"
    mode: '0644'

- name: Symlink zsh dotfiles to home directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: true
    follow: false
  loop:
    - .alias.zsh
    - .zshrc
