- name: Set up local workstation
  hosts: local
  gather_facts: yes
  roles:
    - role: macos
      when: ansible_facts['os_family'] == 'Darwin'
      tags:
        - macos
    - role: gentoo
      when: ansible_facts['distribution'] == 'Gentoo'
      tags:
        - gentoo
