---
# If non empty, the path where /nix should be bind mount to.
nix_installer_bind_mount: ""

# If true, also install and configure nix flakes
nix_installer_flakes: false

# User to install nix for
nix_installer_user: "{{ ansible_user_id | default(lookup('env', 'USER')) }}"
