---
- name: "Check if plugin is installed: {{ item.name }}"
  ansible.builtin.command: "asdf plugin list"
  register: asdf_plugin_list
  changed_when: false

- name: "Add plugin: {{ item.name }}"
  ansible.builtin.command: "asdf plugin add {{ item.name }}"
  when: "item.name not in asdf_plugin_list.stdout"
  changed_when: true

- name: "Install language: {{ item.name }} {{ item.version }}"
  ansible.builtin.command: "asdf install {{ item.name }} {{ item.version }}"
  register: install_result
  changed_when: "'is not installed. Installing' in install_result.stdout"
  failed_when:
    - install_result.rc != 0
    - "'is already installed' not in install_result.stderr"

- name: "Set global version: {{ item.name }} to {{ item.version }}"
  ansible.builtin.command: "asdf set -u {{ item.name }} {{ item.version }}"
  register: global_result
  changed_when: "global_result.rc == 0 and 'not installed' not in global_result.stderr"
