---
- name: Set up user and initial directories
  ansible.builtin.include_tasks: setup-user.yml
  tags:
    - nix_user
    - nix_configure

- name: Install the Nix package manager
  ansible.builtin.include_tasks: install-nix.yml
  tags:
    - nix_install

- name: Configure Nix Flakes
  ansible.builtin.include_tasks: setup-flakes.yml
  when: nix_flakes | default(false)
  tags:
    - nix_flakes
    - nix_configure
