---
- name: Set up user and initial directories
  ansible.builtin.include_tasks: setup-user.yml

- name: Install the Nix package manager
  ansible.builtin.include_tasks: install-nix.yml

- name: Configure Nix Flakes
  ansible.builtin.include_tasks: setup-flakes.yml
  when: nix_flakes | default(false)
