- name: Ensure eselect-repository is installed
  become: true
  portage:
    name: app-eselect/eselect-repository
    state: present

- name: Enable Guru repository
  become: true
  command:
    cmd: eselect repository enable guru
  register: guru_repo
  changed_when: "'enabled' in guru_repo.stdout"

- name: Sync the Guru repository
  become: true
  command:
    cmd: emaint sync -r guru
  when: guru_repo.changed

- name: Install Hyprland and the addition packages in the GURU overlay
  become: true
  loop:
    - gui-wm/hyprland
    - gui-apps/hyprlock
    - gui-apps/hypridle
    - gui-libs/xdg-desktop-portal-hyprland
    - gui-apps/hyprpaper
    - gui-apps/hyprpicker
    - gui-wm/hyprland-contrib
  portage:
    name: "{{ item }}"
    verbose: true
    state: present
