- name: Install packages
  become: true
  loop:
    - app-editors/neovim
    - app-misc/jq
    - app-misc/tmux
    - app-portage/gentoolkit
    - app-shells/fzf
    - app-shells/starship
    - app-shells/zoxide
    - app-shells/zsh
    - dev-lang/fennel
    - dev-qt/qtwayland
    - dev-util/wakatime-cli
    - dev-vcs/git
    - dev-vcs/lazygit
    - gui-apps/mako
    - gui-apps/wofi
    - gui-apps/waybar
    - kde-apps/dolphin
    - media-fonts/font-isas-misc
    - media-fonts/arphicfonts
    - media-fonts/opendesktop-fonts
    - media-fonts/wqy-zenhei
    - media-fonts/zh-kcfonts
    - media-video/libva-utils
    - sys-apps/bat
    - sys-apps/eza
    - sys-apps/fd
    - sys-apps/ripgrep
  portage:
    name: "{{ item }}"
    verbose: true
    state: present
