#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="4"
gaps["bottom"]="24"
gaps["left"]="4"
gaps["right"]="4"
gaps["inner"]="4"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================
yabai -m config layout bsp

yabai -m config external_bar all:$(sketchybar --query bar | jq .height):0

yabai -m config top_padding "${gaps["top"]}"
yabai -m config bottom_padding "${gaps["bottom"]}"
yabai -m config left_padding "${gaps["left"]}"
yabai -m config right_padding "${gaps["right"]}"
yabai -m config window_gap "${gaps["inner"]}"

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config window_topmost off
yabai -m config window_shadow float

yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color "${color["focused"]}"
yabai -m config normal_window_border_color "${color["normal"]}"
yabai -m config insert_feedback_color "${color["preselect"]}"

yabai -m config split_ratio 0.50

yabai -m config auto_balance off

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config window_opacity on
yabai -m config active_window_opacity 1
yabai -m config normal_window_opacity 0.9

# ===== Rules ==================================

# disable yabai for these apps
yabai -m rule --add app="^DeepL$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^LibreOffgce$" manage=off
yabai -m rule --add app="^QQ$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
yabai -m rule --add app="^Skype$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^Tencent$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off
yabai -m rule --add app="^WeCom$" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add title="^Ivory$" manage=off

yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pulse Secure$" manage=off
yabai -m rule --add app="^Finder$" manage=off

yabai -m rule --add app="^Print Center$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add title="^Preferences$" manage=off
yabai -m rule --add title="^Digital Colour Meter$" manage=off
yabai -m rule --add title="^General.*" manage=off
yabai -m rule --add title="^QuickTime$" manage=off

yabai -m space 1 --label Terminal
yabai -m space 2 --label Browser
yabai -m space 3 --label Code
yabai -m space 4 --label Messages
yabai -m space 5 --label 5
yabai -m space 6 --label 6
yabai -m space 7 --label 7
yabai -m space 8 --label 8
yabai -m space 9 --label 9

yabai -m rule --add app="^Alacritty$" space=1
yabai -m rule --add app="^Safari$" space=2
yabai -m rule --add app="IntelliJ IDEA" space=3
yabai -m rule --add app="Obsidian" space=5

set +x
printf "yabai: configuration loaded...\\n"

yabai -m rule --apply
