hl.on("hyprland.start", function ()
    hl.exec_cmd("waybar")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("fcitx5-remote -r")
    hl.exec_cmd("fcitx5 -d --replace")
    hl.exec_cmd("fcitx5-remote -r")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("~/.config/hypr/xdg-portal-hyprland")
    hl.exec_cmd("~/.config/hypr/scripts/wallpaper.sh")

    hl.exec_cmd("[workspace 1] alacritty")
    hl.exec_cmd("[workspace 2 silent] firefox")
    hl.exec_cmd("[workspace 3 silent] google-chrome-stable")
    hl.exec_cmd("[workspace 3 silent] obsidian --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations --enable-wayland-ime")
    hl.exec_cmd("[workspace 4 silent] kitty")
    hl.exec_cmd("[workspace 5 silent] Telegram")
    hl.exec_cmd("[workspace 5 silent] flatpak run com.tencent.WeChat")
end)
