# Check if gpakosz/.tmux is installed
- name: Check if gpakosz/.tmux is installed
  command: ls ~/.tmux
  register: tmux_installed
  ignore_errors: true

# clone https://github.com/gpakosz/.tmux
- name: Clone gpakosz/.tmux
  git:
    repo: https://github.com/gpakosz/.tmux
    dest: ~/.tmux
  when: not tmux_installed.stdout

- name: Check if tpm is installed
  command: ls ~/.tmux/plugins/tpm
  register: tpm_installed
  ignore_errors: true

- name: Clone tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  when: not tpm_installed.stdout

# Symlink .tmux.conf to ~
- name: Symlink .tmux.conf to ~
  file:
    src: "~/.tmux/.tmux.conf"
    dest: "~/.tmux.conf"
    state: link

# Symlink .tmux.conf.local to ~
- name: Symlink .tmux.conf.local to ~
  file:
    src: "{{ playbook_dir }}/common/.tmux.conf.local"
    dest: "~/.tmux.conf.local"
    state: link
