- name: Check if zsh is the default shell
  command: echo $SHELL
  register: shell

- name: Sets zsh as the default shell
  command: chsh -s /bin/zsh
  become: true
  become_user: root
  when: shell.stdout != "/bin/zsh"

- name: Check if ohmyzsh is installed
  command: ls ~/.oh-my-zsh
  register: ohmyzsh_installed
  ignore_errors: true

- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_installed.stdout

- name: Symlink zsh dotfiles to ~
  loop:
    - .alias.zsh
    - .env.zsh
    - .zshrc
  file:
    src: "{{ playbook_dir }}/common/zsh/{{ item }}"
    dest: "~/{{ item }}"
    state: link
