---
- name: Ensure target directory for .desktop files exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/applications"
    state: directory
    mode: '0755'

- name: Find all custom .desktop files in the role
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    patterns: "*.desktop"
  register: desktop_files

- name: Symlink custom .desktop files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_user_dir }}/.local/share/applications/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ desktop_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
