---
- name: "Check if plugin is already installed: {{ item.name }}"
  ansible.builtin.command: "asdf plugin list | grep '{{ item.name }}'"
  register: plugin_check
  changed_when: false
  failed_when: false

- name: "Add plugin: {{ item.name }}"
  ansible.builtin.command: "asdf plugin add {{ item.name }}"
  when: plugin_check.rc != 0
  changed_when: true

- name: "Install language: {{ item.name }} {{ item.version }}"
  ansible.builtin.command: "asdf install {{ item.name }} {{ item.version }}"
  register: install_result
  changed_when: "'is not installed. Installing' in install_result.stdout"
  failed_when:
    - install_result.rc != 0
    - "'is already installed' not in install_result.stderr"

- name: "Set global version for {{ item.name }}"
  ansible.builtin.command: "asdf set -u {{ item.name }} {{ item.version }}"
  ignore_errors: true
