---
- name: Install packages with flatpak
  flatpak:
    name:
      - com.bitwarden.desktop
      - com.github.tchx84.Flatseal
      - com.rustdesk.RustDesk
      - com.slack.Slack
      - com.synology.SynologyDrive
      - com.usebruno.Bruno
      - com.visualstudio.code
      - io.beekeeperstudio.Studio
      - io.httpie.Httpie
      - io.missioncenter.MissionCenter
      - md.obsidian.Obsidian
      - one.ablaze.floorp
      - org.deskflow.deskflow
      - org.kde.dolphin
      - org.jupyter.JupyterLab
      - org.telegram.desktop
    state: present
    method: user
