---
- name: Ensure correct ownership of .nix-defexpr
  become: true
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.nix-defexpr"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
    recurse: true

- name: Add the nixpkgs channel for the user
  ansible.builtin.shell:
    cmd: |
      . {{ ansible_env.HOME }}/.nix-profile/etc/profile.d/nix.sh
      nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    executable: /bin/zsh
  args:
    creates: "{{ ansible_env.HOME }}/.nix-defexpr/channels/nixpkgs"

- name: Add the home-manager channel
  ansible.builtin.shell:
    cmd: |
      . {{ ansible_env.HOME }}/.nix-profile/etc/profile.d/nix.sh
      nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    executable: /bin/zsh
  args:
    creates: "{{ ansible_env.HOME }}/.nix-defexpr/channels/home-manager"

- name: Update Nix channels
  ansible.builtin.shell:
    cmd: ". {{ ansible_env.HOME }}/.nix-profile/etc/profile.d/nix.sh && nix-channel --update"
    executable: /bin/zsh
  changed_when: true

- name: Install Home Manager
  ansible.builtin.shell:
    cmd: |
      nix-shell '<home-manager>' -A install
    executable: /bin/zsh
  args:
    creates: "{{ ansible_env.HOME }}/.nix-profile/bin/home-manager"

- name: Apply the Home-Manager configuration using Flakes
  ansible.builtin.shell:
    cmd: |
      . {{ ansible_env.HOME }}/.nix-profile/etc/profile.d/nix.sh
      home-manager switch --flake {{ playbook_dir }}/../nix/#{{ ansible_distribution | lower }}
    executable: /bin/zsh
  register: home_manager_switch
  changed_when: "'activating' in home_manager_switch.stdout or 'building' in home_manager_switch.stdout"
