---
- name: Add nixpkgs channel if missing
  ansible.builtin.command: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  args:
    creates: "{{ ansible_env.HOME }}/.nix-defexpr/channels/nixpkgs"
  register: add_nixpkgs
  changed_when: add_nixpkgs.rc == 0

- name: Add the home-manager channel
  ansible.builtin.command: nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
  args:
    creates: ~/.nix-defexpr/channels/home-manager

- name: Update Nix channels
  ansible.builtin.command: nix-channel --update

- name: Ensure home-manager is installed
  ansible.builtin.command: nix-shell '<home-manager>' -A install

- name: Ensure nixpkgs config directory exists
  ansible.builtin.file:
    path: ~/.config/nixpkgs
    state: directory
    mode: '0755'

- name: Copy home.nix configuration
  ansible.builtin.copy:
    src: home.nix
    dest: ~/.config/nixpkgs/home.nix
    mode: '0644'

- name: Apply home-manager configuration
  ansible.builtin.command: home-manager switch
  register: home_manager_switch
  changed_when: "'these changes will be activated' in home_manager_switch.stdout"
