---
migrate_storage_libvirt_service: "libvirtd"
migrate_storage_kvm_source_dir: "/var/lib/libvirt/images"
migrate_storage_kvm_target_dir: "/home/libvirt/images"
migrate_storage_portage_make_conf: "/etc/portage/make.conf"
migrate_storage_distfiles_source_dir: "/var/cache/distfiles"
migrate_storage_distfiles_target_dir: "/home/gentoo/distfiles"
