- name: Configure portage files
  become: true
  register: portage_files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - src: make.conf.j2
      dest: /etc/portage/make.conf
    - src: package.license.j2
      dest: /etc/portage/package.license
    - src: package.use/sys.j2
      dest: /etc/portage/package.use/sys
    - src: package.use/cli.j2
      dest: /etc/portage/package.use/cli
    - src: package.use/gui.j2
      dest: /etc/portage/package.use/gui
    - src: package.accept_keywords/sys.j2
      dest: /etc/portage/package.accept_keywords/sys
    - src: package.accept_keywords/cli.j2
      dest: /etc/portage/package.accept_keywords/cli
    - src: package.accept_keywords/gui.j2
      dest: /etc/portage/package.accept_keywords/gui

- name: Update portage
  become: true
  command: emerge --sync
  when: portage_files.changed

- name: Install packages
  become: true
  loop:
    - app-editors/neovim
    - app-misc/jq
    - app-misc/tmux
    - app-portage/gentoolkit
    - app-shells/fzf
    - app-shells/starship
    - app-shells/zoxide
    - app-shells/zsh
    - dev-lang/fennel
    - dev-qt/qtwayland
    - dev-vcs/git
    - dev-util/android-studio
    - gui-apps/mako
    - gui-apps/waybar
    - kde-apps/dolphin
    - media-fonts/font-isas-misc
    - media-fonts/arphicfonts
    - media-fonts/opendesktop-fonts
    - media-fonts/wqy-zenhei
    - media-fonts/zh-kcfonts
    - media-sound/pavucontrol
    - media-sound/playerctl
    - media-video/ffmpeg
    - net-wireless/wpa_supplicant
    - sys-apps/bat
    - sys-apps/eza
    - sys-apps/fd
    - sys-apps/ripgrep
    - sys-process/bottom
    - sys-kernel/dkms
    - www-client/vivaldi
    - x11-terms/alacritty
  portage:
    name: "{{ item }}"
    verbose: true
    state: present

- name: Ensure eselect-repository is installed
  become: true
  portage:
    name: app-eselect/eselect-repository
    state: present

- name: Enable Guru repository
  become: true
  command:
    cmd: eselect repository enable guru
  register: guru_repo
  changed_when: "'enabled' in guru_repo.stdout"

- name: Sync the Guru repository
  become: true
  command:
    cmd: emaint sync -r guru
  when: guru_repo.changed

- name: Enable Gentoo-ZH repository
  become: true
  command:
    cmd: eselect repository enable gentoo-zh
  register: gentoo_zh_repo
  changed_when: "'enabled' in gentoo_zh_repo.stdout"

- name: Sync the Gentoo-ZH repository
  become: true
  command:
    cmd: emaint sync -r gentoo-zh
  when: gentoo_zh_repo.changed

- name: Install Hyprland and the addition packages in the GURU overlay
  become: true
  loop:
    - gui-apps/hypridle
    - gui-apps/hyprlock
    - gui-apps/hyprpaper
    - gui-apps/hyprpicker
    - gui-libs/xdg-desktop-portal-hyprland
    - gui-wm/hyprland
    - gui-wm/hyprland-contrib
  portage:
    name: "{{ item }}"
    verbose: true
    state: present

- name: Install packages from the Guru overlay
  become: true
  loop:
    - dev-util/wakatime-cli
    - dev-vcs/lazygit
    - gui-apps/wlogout
    - gui-apps/wofi
  portage:
    name: "{{ item }}"
    verbose: true
    state: present

- name: Install packages from the Gentoo-ZH overlay
  become: true
  loop:
    - app-i18n/fcitx
    - app-i18n/fcitx-rime
    - app-i18n/fcitx-qt
    - app-i18n/fcitx-gtk
    - app-i18n/fcitx-configtool
  portage:
    name: "{{ item }}"
    verbose: true
    state: present

- name: Remove unneeded packages
  become: true
  portage:
    depclean: true
