---
- name: Configure portage files
  become: true
  register: portage_files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - src: make.conf.j2
      dest: /etc/portage/make.conf
    - src: package.license.j2
      dest: /etc/portage/package.license
    - src: package.use/sys.j2
      dest: /etc/portage/package.use/sys
    - src: package.use/cli.j2
      dest: /etc/portage/package.use/cli
    - src: package.use/gui.j2
      dest: /etc/portage/package.use/gui
    - src: package.accept_keywords/sys.j2
      dest: /etc/portage/package.accept_keywords/sys
    - src: package.accept_keywords/cli.j2
      dest: /etc/portage/package.accept_keywords/cli
    - src: package.accept_keywords/gui.j2
      dest: /etc/portage/package.accept_keywords/gui
    - src: package.unmask.j2
      dest: /etc/portage/package.unmask

- name: Update portage
  become: true
  command: emerge --sync
  when: portage_files.changed

- name: Install packages
  become: true
  portage:
    name:
      - app-containers/podman
      - app-crypt/swtpm
      - app-editors/neovim
      - app-editors/vscode
      - app-emulation/qemu
      - app-emulation/libvirt
      - app-emulation/spice
      - app-emulation/virt-manager
      - app-emulation/virt-viewer
      - app-misc/jq
      - app-misc/tmux
      - app-misc/yazi
      - app-office/libreoffice
      - app-portage/gentoolkit
      - app-shells/fzf
      - app-shells/starship
      - app-shells/zoxide
      - app-shells/zsh
      - dev-qt/qtwayland
      - dev-vcs/git
      - dev-util/android-studio
      - dev-util/android-sdk-cmdline-tools
      - dev-util/idea-community
      - gui-apps/swappy
      - gui-apps/tuigreet
      - gui-apps/waybar
      - gui-libs/greetd
      - media-fonts/font-isas-misc
      - media-fonts/arphicfonts
      - media-fonts/opendesktop-fonts
      - media-fonts/powerline-symbols
      - media-fonts/source-han-sans
      - media-fonts/wqy-zenhei
      - media-fonts/zh-kcfonts
      - media-libs/nvidia-vaapi-driver
      - media-sound/pavucontrol
      - media-sound/playerctl
      - media-video/ffmpeg
      - net-misc/chrony
      - net-misc/spice-gtk
      - net-vpn/tailscale
      - net-wireless/wpa_supplicant
      - sys-apps/bat
      - sys-apps/eza
      - sys-apps/fd
      - sys-apps/flatpak
      - sys-apps/ripgrep
      - sys-fs/fuse
      - sys-process/btop
      - sys-process/procs
      - sys-kernel/dkms
      - virtual/opengl
      - www-client/firefox
      - x11-drivers/nvidia-drivers
      - x11-terms/alacritty
      - x11-terms/kitty
      - x11-themes/papirus-icon-theme
    state: present

- name: Ensure eselect-repository is installed
  become: true
  portage:
    name: app-eselect/eselect-repository
    state: present

- name: Enable Guru repository
  become: true
  command:
    cmd: eselect repository enable guru
  register: guru_repo
  changed_when: "'enabled' in guru_repo.stdout"

- name: Sync the Guru repository
  become: true
  command:
    cmd: emaint sync -r guru
  when: guru_repo.changed

- name: Enable Gentoo-ZH repository
  become: true
  command:
    cmd: eselect repository enable gentoo-zh
  register: gentoo_zh_repo
  changed_when: "'enabled' in gentoo_zh_repo.stdout"

- name: Sync the Gentoo-ZH repository
  become: true
  command:
    cmd: emaint sync -r gentoo-zh
  when: gentoo_zh_repo.changed

- name: Install Hyprland and the addition packages in the GURU overlay
  become: true
  portage:
    name:
      - app-office/obsidian
      - dev-util/asdf-vm
      - gui-apps/hypridle
      - gui-apps/hyprlock
      - gui-apps/hyprpicker
      - gui-apps/hyprshot
      - gui-apps/swaync
      - gui-apps/swww
      - gui-libs/xdg-desktop-portal-hyprland
      - gui-wm/hyprland
      - gui-wm/hyprland-contrib
    verbose: true
    state: present

- name: Install packages from the Guru overlay
  become: true
  portage:
    name:
      - app-misc/ngw-look
      - dev-util/wakatime-cli
      - dev-vcs/lazygit
      - gui-apps/wlogout
      - gui-apps/wofi
      - media-fonts/source-han-serif
      - x11-themes/apple-cursor
      - x11-themes/materia-theme
    verbose: true
    state: present

- name: Install packages from the Gentoo-ZH overlay
  become: true
  portage:
    name:
      - app-i18n/fcitx
      - app-i18n/fcitx-rime
      - app-i18n/fcitx-qt
      - app-i18n/fcitx-gtk
      - app-i18n/fcitx-configtool
    verbose: true
    state: present

- name: Remove unneeded packages
  become: true
  portage:
    depclean: true
