---
- name: Ensure eselect-repository is installed
  become: true
  ansible.builtin.portage:
    name: app-eselect/eselect-repository
    state: present
  run_once: true

- name: Enable {{ item.name }} repository
  become: true
  ansible.builtin.command:
    cmd: eselect repository enable {{ item.name }}
  register: repo_status
  changed_when: "'enabled' in repo_status.stdout"
  loop: "{{ portage_overlays }}"
  loop_control:
    label: "{{ item.name }}"

- name: Sync the {{ item.name }} repository
  become: true
  ansible.builtin.command:
    cmd: emaint sync -r {{ item.name }}
  when: repo_status.changed
  loop: "{{ portage_overlays }}"
  loop_control:
    label: "{{ item.name }}"
