---
- name: Include role variables
  ansible.builtin.include_vars: vars/main.yml

- name: Clone tmux configuration and plugin repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: master
    update: true
  loop: "{{ tmux_git_repos }}"
  loop_control:
    label: "{{ item.dest }}"

- name: Symlink tmux configuration files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop: "{{ tmux_symlinks }}"
  loop_control:
    label: "{{ item.dest }}"
