---
dependencies:
  - role: common
  - role: grub
    tags: grub
  - role: portage
    tags: portage
  - role: hypr
    tags: hypr
  - role: swaync
    tags: swaync
  - role: waybar
    tags: waybar
  - role: wofi
    tags: wofi
  - role: wlogout
    tags: wlogout
  - role: greetd
    tags: greetd
  - role: flatpak
    tags: flatpak
  - role: desktop_launchers
    tags: desktop_launchers
