galaxy_info:
  author: "centsent"
  description: "A role to deploy my personal Rime configuration."
  license: "MIT"
  min_ansible_version: "2.9"
  namespace: "centsent"
  role_name: "rime"
  platforms:
    - name: "Gentoo"
      versions:
        - all
    - name: macOS
      versions:
        - all

dependencies: []
