---
- name: Check if homebrew is installed
  command: brew --version
  register: homebrew_installed
  ignore_errors: true

- name: Install homebrew
  command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not homebrew_installed.stdout

- name: Install packages
  loop:
    - age
    - alacritty
    - android-studio
    - android-platform-tools
    - beekeeper-studio
    - eza
    - fd
    - fennel
    - fnlfmt
    - fzf
    - git
    - glow
    - hoppscotch
    - intellij-idea-ce
    - jq
    - krita
    - libreoffice
    - lazygit
    - neovim
    - obsidian
    - orbstack
    - pika
    - raycast
    - ripgrep
    - shottr
    - skhd
    - sops
    - starship
    - stats
    - topgrade
    - visual-studio-code
    - vivaldi
    - wakatime-cli
    - wormhole
    - yabai
    - yt-dlp
    - zsh
  homebrew:
    name: "{{ item }}"
    state: present
