#!/bin/bash

dbus-update-activation-environment --systemd \
	DISPLAY \
	HYPRLAND_INSTANCE_SIGNATURE \
	WAYLAND_DISPLAY \
	XDG_CURRENT_DESKTOP \
	XDG_SESSION_TYPE

systemctl --user restart xdg-desktop-portal-hyprland.service
systemctl --user restart xdg-desktop-portal.service
