---
- name: Sync the Portage tree
  become: true
  ansible.builtin.portage:
    sync: true
  tags:
    - gentoo_update
    - skip_ansible_lint

- name: Update all packages on the system (@world)
  become: true
  ansible.builtin.portage:
    package: "@world"
    update: true
    newuse: true
    deep: true
    verbose: true
  tags:
    - gentoo_update

- name: Run depclean to remove obsolete packages
  become: true
  ansible.builtin.portage:
    depclean: true
  tags:
    - gentoo_update
