---
- name: Sync the Portage tree
  become: true
  ansible.builtin.portage:
    sync: yes
  tags:
    - gentoo_update
    - skip_ansible_lint

- name: Update all packages on the system (@world)
  become: true
  ansible.builtin.portage:
    package: "@world"
    update: yes
    newuse: yes
    deep: yes
    verbose: yes
  tags:
    - gentoo_update

- name: Run depclean to remove obsolete packages
  become: true
  ansible.builtin.portage:
    depclean: yes
  tags:
    - gentoo_update
