---
- name: Install packages from Gentoo repository
  become: true
  ansible.builtin.portage:
    name: "{{ portage_packages }}"
    state: present
    verbose: true

- name: Install packages from overlays
  become: true
  ansible.builtin.portage:
    name: "{{ item.packages }}"
    state: present
    verbose: true
  loop: "{{ portage_overlays }}"
  loop_control:
    label: "{{ item.name }}"
