---
- name: Configure portage system files
  ansible.builtin.include_tasks: configure_files.yml

- name: Enable and sync overlays
  ansible.builtin.include_tasks: manage_overlays.yml

- name: Install all packages
  ansible.builtin.include_tasks: install_packages.yml

- name: Remove unneeded packages
  become: true
  community.general.portage:
    depclean: true
