---
- name: "Check if repository '{{ item.name }}' directory exists"
  become: true
  ansible.builtin.stat:
    path: "/var/db/repos/{{ item.name }}"
  register: repo_stat

- name: "Add repository: {{ item.name }}"
  become: true
  ansible.builtin.command:
    cmd: "eselect repository add {{ item.name }} git {{ item.location }}"
  when:
    - not repo_stat.stat.exists
    - item.location is defined
  register: repo_add_result

- name: "Enable repository: {{ item.name }}"
  become: true
  ansible.builtin.command:
    cmd: "eselect repository enable {{ item.name }}"
  register: portage_enable_result
  changed_when: "'enabled' in portage_enable_result.stdout"

- name: "Sync repository: {{ item.name }}"
  become: true
  ansible.builtin.command:
    cmd: "emaint sync -r {{ item.name }}"
  when: portage_enable_result.changed or (repo_add_result is defined and repo_add_result.changed)
  tags:
    - skip_ansible_lint
