---
- name: "Enable repository: {{ item.name }}"
  become: true
  ansible.builtin.command:
    cmd: "eselect repository enable {{ item.name }}"
  register: portage_enable_result
  changed_when: "'enabled' in portage_enable_result.stdout"

- name: "Sync repository: {{ item.name }}"
  become: true
  ansible.builtin.command:
    cmd: "emaint sync -r {{ item.name }}"
  when: portage_enable_result.changed
  tags:
    - skip_ansible_lint
