[tools]
bun = "latest"
dotnet = "latest"
flutter = "latest"
go = "latest"
java = "21"
nodejs = "lts"
pnpm = "latest"
python = "3.13"
rust = "stable"

pipx = "latest"
"pipx:sqlfluff" = "latest"

mkcert = "latest"
