- name: Configure /etc/default/grub
  become: true
  register: grub_template
  template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644

- name: Update GRUB configuration
  become: true
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub_template.changed
