---
- name: Configure /etc/default/grub
  become: true
  register: grub_template
  ansilble.builtin.template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  notify: Update GRUB configuration
