---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate Ansible Project
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Ansible Galaxy role dependencies
        run: ansible-galaxy install -r requirements.yml

      - name: Install required Ansible Collections
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install ansible.windows

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main

      - name: Syntax-check all main playbooks
        run: |
          echo "localhost ansible_connection=local" > inventory_for_test
          ansible-playbook -i inventory_for_test ./macos.yml --syntax-check
          ansible-playbook -i inventory_for_test ./gentoo.yml --syntax-check
          ansible-playbook -i inventory_for_test ./update.yml --syntax-check
